name: Task-02-Tests-Workflow
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #Task4
        python-version: [3.7, 3.8, 3.9]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install  dependencies
      run: pip install -r requirements.txt || true
    - name: test run
      run: python -m unittest discover tests

