name: Task-02-Tests-Workflow
on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: python setup
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install  dependencies
      run: pip install -f requirements.txt || true
    - name: test run
      run: python -m unittest discover tests

